# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.listView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 3, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.creat_button = QtWidgets.QPushButton(self.centralwidget)
        self.creat_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.creat_button.sizePolicy().hasHeightForWidth())
        self.creat_button.setSizePolicy(sizePolicy)
        self.creat_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(180, 180, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/create.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.creat_button.setIcon(icon)
        self.creat_button.setIconSize(QtCore.QSize(128, 128))
        self.creat_button.setCheckable(False)
        self.creat_button.setChecked(False)
        self.creat_button.setAutoDefault(False)
        self.creat_button.setObjectName("creat_button")
        self.horizontalLayout.addWidget(self.creat_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button.sizePolicy().hasHeightForWidth())
        self.open_button.setSizePolicy(sizePolicy)
        self.open_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(180, 180, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid;\n"
"}")
        self.open_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_button.setIcon(icon1)
        self.open_button.setIconSize(QtCore.QSize(128, 128))
        self.open_button.setObjectName("open_button")
        self.horizontalLayout.addWidget(self.open_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.file_menu.setObjectName("file_menu")
        self.setting_menu = QtWidgets.QMenu(self.menubar)
        self.setting_menu.setGeometry(QtCore.QRect(403, 185, 148, 72))
        self.setting_menu.setObjectName("setting_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action114 = QtWidgets.QAction(MainWindow)
        self.action114.setObjectName("action114")
        self.create_menu = QtWidgets.QAction(MainWindow)
        self.create_menu.setObjectName("create_menu")
        self.open_menu = QtWidgets.QAction(MainWindow)
        self.open_menu.setObjectName("open_menu")
        self.about_menu = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/logo128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_menu.setIcon(icon2)
        self.about_menu.setObjectName("about_menu")
        self.file_menu.addAction(self.open_menu)
        self.setting_menu.addAction(self.create_menu)
        self.help_menu.addAction(self.about_menu)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.setting_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QEMU-GUI MainWindow"))
        self.file_menu.setTitle(_translate("MainWindow", "文件(&F)"))
        self.setting_menu.setTitle(_translate("MainWindow", "工具(&S)"))
        self.help_menu.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.action114.setText(_translate("MainWindow", "114"))
        self.create_menu.setText(_translate("MainWindow", "新建虚拟硬盘(&C)"))
        self.open_menu.setText(_translate("MainWindow", "打开(&O)"))
        self.about_menu.setText(_translate("MainWindow", "关于 QEMU-GUI(&A)"))
