# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'create_vhd_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import os

from PyQt5.QtWidgets import QMainWindow

from create_vhd_window import Ui_CreateVHDWindow

create_vhd_window = uic.loadUiType(
    f"{os.path.dirname(__file__)}\\create_vhd_window.ui"
)[0]


class CreateVHDWindow(QtWidgets.QMainWindow, create_vhd_window):
    def __init__(self, parent=None):
        super(CreateVHDWindow, self).__init__(parent)
        self.setupUi(self)
        self.CancelButton.clicked.connect(self.exit)

        self.format_list = {}

        self.setWindowIcon(
            QtGui.QIcon(f"{os.path.dirname(__file__)}\\..\\img\\qemu.ico")
        )

        self.About.triggered.connect(self.show_about_window)
        self.set_combo()

    def show_about_window(self):
        from ui.about_create_vhd_window import Ui_AboutCreateVHDWindow

        self.window = QMainWindow()
        ui = Ui_AboutCreateVHDWindow()
        ui.setupUi(self.window)
        self.window.setWindowIcon(
            QtGui.QIcon(f"{os.path.dirname(__file__)}\\..\\img\\qemu.ico")
        )
        self.window.show()

    def show_introduce(self, index):
        self.introduce.setText(list(self.format_list.values())[index])
        # print(list(self.format_list.values())[index])
        print(len(list(self.format_list.values())[index]))
        if len(list(self.format_list.values())[index]) > 50:
            self.introduce.setWordWrap(True)
            self.introduce.setFixedWidth(550)
        else:
            self.introduce.setWordWrap(False)

    def set_combo(self):
        with open(
            f"{os.path.dirname(__file__)}\\..\\支持格式.txt", "r", encoding="utf-8"
        ) as f:
            for i in f.readlines():
                self.format_list[i.split("：")[0]] = i.split("：")[1]
        self.format.addItems(list(self.format_list.keys()))
        self.format.activated.connect(self.show_introduce)
        self.introduce.setText(self.format_list["qcow2"])
        self.introduce.setWordWrap(True)
        self.introduce.setFixedWidth(550)

    def exit(self):
        self.close()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ui = CreateVHDWindow()

    ui.show()
    sys.exit(app.exec_())
